= About this text


This work, "Discrete Math - The MKD Remix", 
by 
https://github.com/m-k-davis/[Mark Kelly Davis], 
is adapted from 
https://ggc-discrete-math.github.io/index.html[“Discrete Math”], 
by 
//a group of mathematics and information technology professors 
//at Georgia Gwinnett College, namely, 
https://www.ggc.edu/directory/mohamed-jamaloodeen[Mohamed Jamaloodeen], 
https://www.ggc.edu/directory/katherine-pinzon[Kathy Pinzon], 
https://www.ggc.edu/directory/daniel-pragel[Daniel Pragel], 
https://www.ggc.edu/directory/joshua-roberts[Joshua Roberts], and https://www.ggc.edu/directory/sebastien-siva[Sebastien Siva]. 
https://ggc-discrete-math.github.io/index.html[“Discrete Math”] is used under https://creativecommons.org/licenses/by-nc/4.0/[CC BY-NC 4.0]. 
All files for 
https://ggc-discrete-math.github.io/index.html[“Discrete Math”] 
are available at its associated 
https://github.com/ggc-discrete-math/ggc-discrete-math.github.io[GitHub repository]. 

This work, "Discrete Math - The MKD Remix", 
is licensed under 
https://creativecommons.org/licenses/by-nc/4.0/[CC BY-NC 4.0] 
by Mark Kelly Davis.


== How does the MKD Remix differ from the original work?

Here is a partial list of changes made (or to be made) to the original. 

* Throughout the remix, definitions were changed to align with ones found in other commonly-used textbooks. One example: The remix defines the natural numbers $\mathbb{N}$ to include the integer $0$ as a member.

* Some existing code snippets were altered. New code snippets were introduced throughout the remix.

* Informal definitions of several core concepts were inserted in the chapter "Introducing Discrete Mathematics". 

* The chapter "Introduction to Python" was moved to the appendices. In this book, Python is used as a tool for understanding abstract concepts that are important to discrete mathematics, but Python is not a part of the course content.

* The order of the chapters "Set Theory" and "Logic" were swapped. New material was inserted into each of the two chapters.

* A new chapter, "Proofs," was written and inserted after the chapter on Logic.

* The old chapter "Sequences, Recursive Definitions, and Induction" was broken into two new chapters, "Sequences and Recursive Definitions" and "Induction". The new chapter "Induction" was heavily rewritten and new content was inserted.


////
MKD: NEED TO EDIT ALL ORIGINAL TEXT BELOW.

== Additional Resources

Additional instructional materials, including guided notes, applets, and links to pre-built homework assignments using https://edfinity.com/[Edfinity] are available in the book's https://github.com/ggc-discrete-math/ggc-discrete-math.github.io#readme[GitHub readme page].

Please report any errors, suggestions, or comments using the form at https://forms.office.com/Pages/ResponsePage.aspx?id=21KVzwpmkUqb1mXCMA-cscUcLDJuuLtGtmN7hxi3Vs9URFcyMDhSWTBZWkxIVzlZRjJVVzVXUThZVS4u[this link].

== Course Objectives

At Georgia Gwinnett College, students who have successfully completed the Discrete Mathematics course will,

. Reason mathematically and use mathematical language appropriately to demonstrate an understanding of comprehending and constructing mathematical arguments.
. Perform combinatorial analysis to solve counting problems and analyze algorithms.
. Demonstrate an understanding of discrete structures including sets, permutations, relations, graphs, and trees.
. Demonstrate algorithmic thinking using mathematical creativity and critical thinking by specifying algorithms, verifying that algorithms work, and analyzing the time required to perform specific algorithms.
. Use appropriate technology in the evaluation, analysis, and synthesis of information in problem-solving situations.

These course goals help structure the content of this class, which is
aimed at students of
information technology, computer science, and applied mathematics.  The focus is on applying
discrete math techniques from the two broad component areas of discrete
math, namely
combinatorics or enumerative techniques, and graph theory.

To that end, algorithmic thinking figures
prominently in this course.
Designing algorithms, particularly algorithms
applied to networks, involves the use of graph theory methods. Implementing algorithms
requires a careful understanding of logical structures, and usually a top down implementation
approach, beginning with a specifications description,  and then proceeding
to a pseudocode implementation and finally a language dependent coding
implementation. Moreover, analyzing the complexity of algorithms requires a knowledge of functions,
the growth of functions, and counting techniques from combinatorial analysis.  Similarly, mathematical induction and recursive
definitions are used in a cohesive way to understand algorithms and the options in implementing these
recursively versus iteratively.

The approach we take is one with an integrative incorporation of programming and
algorithms into the course. The aim is to help improve students success
with their broad programming curricula in courses like Intermediate and Advanced Programming.
////
