= Relations

#*CAUTION* - CHAPTER UNDER CONSTRUCTION!#

_This chapter was last updated on October 14, 2024._

COMING SOON!

////
RELATIONS (MKD) - new chapter is needed for this
	ACM CCECC Set/rels/funcs/congruence	
    COMP 152 Functions, Relations and Sets and DS1.
		relations including 
			equivalence relations, 
			equivalence classes
        Relations (
        	reflexivity, 
        	symmetry, 
        	transitivity, 
        	equivalence relations)
	MKD: add Divisibility 
	MKD: add Congruence and Modular Arithmetic (Operations on Congruence Classes)
	MKD: Also check slides (James Wong, etc.) for examples, etc.
	2013 changes/additions:
		Reflexivity, symmetry, transitivity
		Equivalence relations, partial orders
	[Core-Tier2]
			Well orderings


// MKD may also introduce "Well orderings" here
//	should be spelled "well-ordering"

AUG 2024 update on topics
DS2013/Sets, Relations, and Functions	Relations: Reflexivity, symmetry, transitivity
DS2013/Sets, Relations, and Functions	Relations: Equivalence relations, partial orders
DS2008/FunctionsRelationsAndSets	Relations (reflexivity, symmetry, transitivity, equivalence relations)
ACM_CCECC_2005/Sets, relations, functions, congruences	relations including equivalence relations, equivalence classes

AUG 2024 update on topics (modular arithmetic)
DS2013/Basics of Counting	Basic modular arithmetic

---
Also: JWong includes id_{A} (the identity relation on A)
NOTE: NEED A NEW CHAPTER ON RELATIONS
Relations
Binary relations - examples, inverses and compositions
Identity relation Id
Properties: 
	Reflexive (Id is a subset), Irreflexive (is disjoint from Id)
	Symmetric (equals its own inverse), Antisymmetric (intersection with inverse is a subset of Id)
	Transitive (composition with self is a subset of self)

Definition: A binary relation Rα on a set S is the closure of a relation R on S with respect to property P if
(a) Rα has property P, (b)R ⊆ Rα and
(c) Rα is a smallest relation on S that includes R and has property P.

Definition: Let R be any binary relation on S, then
R ∪ Id is called reflexive closure of R R ∪ R-1 is called symmetric closure of R R+ is called transitive closure of R
R* is called reflexive and transitive closure of R
Example: For a digraph, (a,b) in transitive closure = “there exists a path from (a,b)”

equivalence relation: reflexive, symmetric, and transitive
	these correspond to partitions of the set into equivalence classes (classic example is Odd and Even integers) - Partition is defined in Set Theory chapter and/or Intro chapter.


partial ordering on S is reflexive, antisymmetric, and transitive

Definition: Relations on Multiple Sets Given two sets S and T, a binary relation from S to
T is a subset of S x T. Given n sets S1, S2, ...Sn, n > 2, an n-ary relation on
S1 xS2 x...xSn isasubset of S1 xS2 x...xSn.


Intro. to Relational Databases Let us take a look at a type of database representation that is based on relations, namely the relational data model.
A database consists of n-tuples called records, which are made up of fields. These fields are the entries of the n-tuples.
The relational data model represents a database as an n-ary relation, that is, a set of records

Example: Consider a database of students, whose records are represented as 4-tuples with the fields Student Name, ID Number, Major, and GPA:
R = {
(Ackermann, 231455, CS, 3.88),
(Adams, 888323, Physics, 3.45), (Chou, 102147, CS, 3.79),
(Goodfriend, 453876, Math, 3.45), (Rao, 678543, Math, 3.90),
(Stevens, 786576, Psych, 2.99)}
Relations that represent databases are also called tables, since they are often displayed as tables.
We can apply a variety of operations on n-ary relations to form new relations.

Definition: The projection Pi1, i2, ..., im maps the n-tuple (a1, a2, ..., an) to the m-tuple (ai1, ai2, ..., aim), where m ≤ n. i.e. select some fields from a record
Example: What is the result when we apply the projection P2,4 to the student record (Stevens, 786576, Psych, 2.99) ?
Solution: It is the pair (786576, 2.99).
In some cases, applying a projection to an entire table may not only result in fewer columns, but also in fewer rows. (select fields from entire table)
Why is that? Some records may only have differed in those fields that were deleted, so they become identical, and there is no need to list identical records more than once.

We can use the join operation to combine two tables into one if they share some identical fields.
Definition: Let R be a relation of degree m and S a relation of degree n. The join Jp(R, S), where p ≤ m and p ≤ n, is a relation of degree m + n – p that consists of all (m + n – p)- tuples (a1, a2, ..., am-p, c1, c2, ..., cp, b1, b2, ..., bn-p), where the m-tuple (a1, a2, ..., am-p, c1, c2, ..., cp) belongs to R and the n-tuple (c1, c2, ..., cp, b1, b2, ..., bn-p) belongs to S.
In other words, to generate Jp(R, S), we have to find all the elements in R whose p last components match the p first components of an element in S. The new relation contains exactly these matches, which are combined to tuples that contain each matching field only once

Example: What is J1(Y, R), where Y contains the fields Student Name and Year of Birth,
Y = {(1978, Ackermann), (1972, Adams), (1917, Chou), (1984, Goodfriend), (1982, Rao), (1970, Stevens)},
and R contains the student records as defined before ?
Solution: The resulting relation is:
{(1978, Ackermann, 231455, CS, 3.88), (1972, Adams, 888323, Physics, 3.45), (1917, Chou, 102147, CS, 3.79), (1984, Goodfriend, 453876, Math, 3.45), (1982, Rao, 678543, Math, 3.90), (1970, Stevens, 786576, Psych, 2.99)}
Since Y has two fields and R has four, the relation J1(Y, R) has 2 + 4 – 1 = 5 fields.




// MKD content starts Here

//== the basic idea, informally

Informally, a relation on two or more sets is an association between elements of those sets.
//_A_ and _B_ is an association between elements from set _A_ and set _B._ 

Examples: 

* the comparisons we make between two numbers: Is the first number less than, equal to, or greater than the second number? 

* the association of a student's name, the student's ID number, and classes in which the student is enrolled. Here there are three sets: The set of names of all students, the set of all student ID numbers, and the set of all classes offered. Notice that the same name and ID number are likely to be associated with multiple classes.

* the association of siblinghood (e.g., two people are brothers or sisters).

* the association of each integer with its square. This relation is a function. In fact, every function is a relation since it associates an input with exactly one output.



== Definition of _n_-ary Relation

Given sets $A_{1}, \, A_{2}, \, \ldots \, A_{n}$ where $n \geq 2,$ 
an *_n_-ary relation* on $A_{1}, \, A_{2}, \, \ldots \, A_{n}$ 
is a subset $R$ of the Cartesian product 
$A_{1} \times A_{2} \times \cdots \times A_{n},$ that is, 
$R \subseteq A_{1} \times A_{2} \times \cdots \times A_{n}.$

The sets $A_{1}, \, A_{2}, \, \ldots \, A_{n}$ are called the *domains* of the relation $R,$ and $n$ is called the *degree* of the relation $R.$


Example: Let 
$A$ be the set of names of students currently enrolled at a college, 
$B$ be the set of all possible student ID numbers, and 
$C$ be the set of all classes currently offered at the college. 
//The set $R = \{ (x, y, z) : \text{Student _x_ has ID number _y_ and has declared major z} \}$ is a 3-ary relation, also called a *ternary relation* on $R \subseteq A \times B \times C.$ 
The set \[ R = \{ (x, y, z) \mid \text{Student } x \text{ has ID number } y \text{ and is enrolled in class } z \} \] is a 3-ary relation, also called a *ternary relation* on $A \times B \times C.$ 

Example: Let 
$A$ be the set of names of students currently enrolled at a college. 
The set \[ R = \{ (x, y) \mid \text{Student } x \text{ is enrolled in a class section in which student } y  \text{ also is enrolled} \} \] is a 2-ary relation, usually called a *binary relation* on $A \times A.$ Most of the focus of this chapter will be on binary relations. 


== Binary Relations

A *binary relation* on sets $A$ and $B$ is any subset $R$ of the cartesian product c, that is, $R \subseteq A \times B.$ 


Example NEEDED where A and B are NOT same set, but not a Functions

Example: Any function f from A to B is a relation 
since $f \subseteq A \times B$ (Recall from link:./functions.html[Functions] that the definition of function means that _f_ is defined to be subset of 
$A \times B.$)


In many cases, the two sets are the same set, and the relation involves a comparison of elements of the set _A._

A *binary relation* on set $A$ is any subset $R$ of the cartesian product 
$A \times A$, that is, $R \subseteq A \times A.$  



=== Examples of Binary Relations on a Set

students enrolled in the same class (out of all students at a college)

ordering on numbers

subset lattice

Divisibility

congruence of integers modulo m

the identity relation $id_{A}$


=== Properties of Binary Relations

reflexive

symmetric

transitivity

irreflexive

antisymmemtric

== Equivalence Relations

Definition

Equivalence Classes (along with odd/even example)

Partition <-> Equivalence Relaction

== Modular Arithmetic

// MKD Challenges
//		Find all n such that n^2 \cong 1 mod 7 (Hint: you can make a table of values of the squaring function)
//		Find all n such that n^2 \cong -1 mod 10 (Hint: What positive numbers are congruent to -1 modulo 10)

== Partial Orderings

// MKD: https://en.wikipedia.org/wiki/Join_and_meet#Examples
//  point out that \subseteq of P(S) forms a lattice (i.e., every subset of P(S) has a join and a meet)

== Total Orderings

===	Well-Ordering


COMING SOON!
////